framework:
    notifier:
        chatter_transports:
            telegram: '%env(TELEGRAM_DSN)%'
        channel_policy:
            urgent: ['telegram']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
